export enum EventEvents {
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_UPDATED = 'EVENT_UPDATED',
  EVENT_DELETED = 'EVENT_DELETED',
  EVENT_STATUS_CHANGE = 'EVENT_STATUS_CHANGE',
  EVENT_METADATA_UPDATE = 'EVENT_METADATA_UPDATE',
}
