export enum TicketEvents {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_CANCELLED = 'TICKET_CANCELLED',
  TICKET_CHECKED_IN = 'TICKET_CHECKED_IN',
  TICKET_REVERT_CHECKED_IN = 'TICKET_REVERT_CHECKED_IN',
  ONLINE_CHECK_IN_REDIRECT = 'ONLINE_CHECK_IN_REDIRECT',
  CUSTOM_ONLINE_JOIN_URL = 'CUSTOM_ONLINE_JOIN_URL',
  TICKET_ASSIGNED_GENERATE_METADATA = 'TICKET_ASSIGNED_GENERATE_METADATA',
}
